### ISSUE TITLE
APU2 boot (via ipxe) failure.

### ISSUE THREAD

**Issue by leszekbulawa** [pcengines/seabios#4]
Booting from ipxe via tftp results in failure for Debian i386/amd64 and OpenBSD. 
Transmission via tftp is ok.

#### Before booting: ####
`unimplemented handle_1aXX:258`
#### After booting Debian: ####
`enter handle_12: invalid handle_legacy_disk:729:`  
`unimplemented handle_15XX:330:`  
`unimplemented handle_16XX:232:`  
then APU2 freezes.
#### After booting OpenBSD: ####
 APU2 reboots

#### Software versions ####
SeaBIOS (version rel-1.9.0-144-gd58a78f)
coreboot-44ac0ed-dirty-4.0.1
[Debian i386](http://ftp.nl.debian.org/debian/dists/jessie/main/installer-i386/current/images/netboot/netboot.tar.gz)
[Debian amd64](http://ftp.debian.org/debian/dists/wheezy/main/installer-amd64/current/images/netboot/netboot.tar.gz)
[OpenBSD](http://ftp.icm.edu.pl/pub/OpenBSD/5.9/amd64/)
[http://ftp.icm.edu.pl/pub/OpenBSD/5.9/amd64/](openbsd)
[iPXE server from](https://github.com/3mdeb/pxe-server)

**Comment by mek-x** [comment]
@miczyg1 please check, that this is still valid issue.

**Comment by miczyg1** [comment]
@mek-x should I check it with SeaBIOS 1.9 or 1.11 or both?

**Comment by mek-x** [comment]
@miczyg1 latest one

**Comment by miczyg1** [comment]
Platform does not reboot neither freezes on the SeaBIOS 1.11.0.1. Every system is booting correctly, the trick is to set output to console properly (refer to https://github.com/3mdeb/netboot). There are no errors like unimplemented handle etc.

**Comment by pietrushnic** [comment]
@miczyg1 since your comment seems to address this issue I'm closing it as no longer relevant.
